apiVersion: apps/v1
kind: Deployment
metadata:
  name: processamento-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processamento-service
  template:
    metadata:
      labels:
        app: processamento-service
    spec:
      containers:
      - name: processamento-service
        image: joaodainese/processamento-service:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: processamento-config
          - secretRef:
              name: processamento-secret
        livenessProbe:
          exec:
            command:
              - pidof
              - dotnet
          initialDelaySeconds: 15
          periodSeconds: 30
          failureThreshold: 3
        resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
            ephemeral-storage: "1Gi"
          limits:
            cpu: "500m"
            memory: "512Mi"
            ephemeral-storage: "2Gi"
