// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414222905_AdicionarDadosOrigem")]
    partial class AdicionarDadosOrigem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.ProcessamentoDiagrama.Aggregates.ProcessamentoDiagrama", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnaliseDiagramaId")
                        .HasColumnType("uuid")
                        .HasColumnName("analise_diagrama_id");

                    b.HasKey("Id");

                    b.HasIndex("AnaliseDiagramaId")
                        .IsUnique();

                    b.ToTable("processamento_diagramas", (string)null);
                });

            modelBuilder.Entity("Domain.ProcessamentoDiagrama.Aggregates.ProcessamentoDiagrama", b =>
                {
                    b.OwnsOne("Domain.ProcessamentoDiagrama.Entities.AnaliseResultado", "AnaliseResultado", b1 =>
                        {
                            b1.Property<Guid>("ProcessamentoDiagramaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ComponentesIdentificados")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("componentes_identificados");

                            b1.Property<string>("RecomendacoesBasicas")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("recomendacoes_basicas");

                            b1.Property<string>("RiscosArquiteturais")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("riscos_arquiteturais");

                            b1.HasKey("ProcessamentoDiagramaId");

                            b1.ToTable("processamento_diagramas");

                            b1.WithOwner()
                                .HasForeignKey("ProcessamentoDiagramaId");

                            b1.OwnsOne("Domain.ProcessamentoDiagrama.ValueObjects.DescricaoAnalise", "DescricaoAnalise", b2 =>
                                {
                                    b2.Property<Guid>("AnaliseResultadoProcessamentoDiagramaId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Valor")
                                        .IsRequired()
                                        .HasMaxLength(10000)
                                        .HasColumnType("character varying(10000)")
                                        .HasColumnName("descricao_analise");

                                    b2.HasKey("AnaliseResultadoProcessamentoDiagramaId");

                                    b2.ToTable("processamento_diagramas");

                                    b2.WithOwner()
                                        .HasForeignKey("AnaliseResultadoProcessamentoDiagramaId");
                                });

                            b1.Navigation("DescricaoAnalise")
                                .IsRequired();
                        });

                    b.OwnsOne("Domain.ProcessamentoDiagrama.Entities.DadosOrigem", "DadosOrigem", b1 =>
                        {
                            b1.Property<Guid>("ProcessamentoDiagramaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Extensao")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("extensao");

                            b1.Property<string>("LocalizacaoUrl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("localizacao_url");

                            b1.Property<string>("NomeFisico")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("nome_fisico");

                            b1.Property<string>("NomeOriginal")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("nome_original");

                            b1.HasKey("ProcessamentoDiagramaId");

                            b1.ToTable("processamento_diagramas");

                            b1.WithOwner()
                                .HasForeignKey("ProcessamentoDiagramaId");
                        });

                    b.OwnsOne("Domain.ProcessamentoDiagrama.ValueObjects.HistoricoTemporal", "HistoricoTemporal", b1 =>
                        {
                            b1.Property<Guid>("ProcessamentoDiagramaId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DataConclusaoProcessamento")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("data_conclusao_processamento");

                            b1.Property<DateTimeOffset>("DataCriacao")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("data_criacao");

                            b1.Property<DateTimeOffset?>("DataInicioProcessamento")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("data_inicio_processamento");

                            b1.HasKey("ProcessamentoDiagramaId");

                            b1.ToTable("processamento_diagramas");

                            b1.WithOwner()
                                .HasForeignKey("ProcessamentoDiagramaId");
                        });

                    b.OwnsOne("Domain.ProcessamentoDiagrama.ValueObjects.StatusProcessamento", "StatusProcessamento", b1 =>
                        {
                            b1.Property<Guid>("ProcessamentoDiagramaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("status_processamento");

                            b1.HasKey("ProcessamentoDiagramaId");

                            b1.ToTable("processamento_diagramas");

                            b1.WithOwner()
                                .HasForeignKey("ProcessamentoDiagramaId");
                        });

                    b.OwnsOne("Domain.ProcessamentoDiagrama.ValueObjects.TentativasProcessamento", "TentativasProcessamento", b1 =>
                        {
                            b1.Property<Guid>("ProcessamentoDiagramaId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Valor")
                                .HasColumnType("integer")
                                .HasColumnName("tentativas_processamento");

                            b1.HasKey("ProcessamentoDiagramaId");

                            b1.ToTable("processamento_diagramas");

                            b1.WithOwner()
                                .HasForeignKey("ProcessamentoDiagramaId");
                        });

                    b.Navigation("AnaliseResultado");

                    b.Navigation("DadosOrigem");

                    b.Navigation("HistoricoTemporal")
                        .IsRequired();

                    b.Navigation("StatusProcessamento")
                        .IsRequired();

                    b.Navigation("TentativasProcessamento")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
